# Generated by Django 5.1.2 on 2024-11-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
